[package]
name = "confy"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
description = "Compile-time configuration file reading"
license = "MIT/Apache-2"
repository = "https://github.com/Luthaf/confy"

[lib]
name = "confy"
plugin = true

[dependencies]
toml = "0.1.27"
